spring:
  application:
    name: java-book-library
  datasource:
    url: jdbc:postgresql://localhost:5432/java_book_library
    username: agents_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
